behaviors:
  DroneAgent:
    trainer_type: ppo

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 4096
      buffer_size: 81920
      learning_rate: 1e-3
      learning_rate_schedule: linear


      # PPO-specific hyperparameters
      beta: 1e-2
      beta_schedule: constant
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
      shared_critic: False


    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 128
      num_layers: 2
      # memory
      memory:
        sequence_length: 64
        memory_size: 256

    # Trainer configurations common to all trainers
    max_steps: 5000000
    time_horizon: 512
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 100000
    threaded: false
    init_path: null

    # behavior cloning
    behavioral_cloning:
      demo_path: F:\Unity_projects\Oblig2\Drone_MLagents\Demos\DroneAgentwow_3.demo
      strength: 0.3
      steps: 250000
      batch_size: 2048
      num_epoch: 3
      samples_per_update: 0

    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.01
        gamma: 0.99
        encoding_size: 256
        learning_rate: 1e-3

      # GAIL
      gail:
        strength: 0.3
        gamma: 0.99
        encoding_size: 128
        demo_path: F:\Unity_projects\Oblig2\Drone_MLagents\Demos\DroneAgentwow_3.demo
        learning_rate: 1e-3
        use_actions: false
        use_vail: false
